#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Redstone.Resource", IsApplication=true)]

namespace Redstone
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060001
			public const int theme_custom_background = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int theme_redstonedefaults_background = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int anvil_base = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int anvil_top_damaged_0 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int anvil_top_damaged_1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int anvil_top_damaged_2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int beacon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bed_feet_end = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bed_feet_side = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bed_feet_top = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int bed_head_end = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int bed_head_side = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int bed_head_top = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int bedrock = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int bookshelf = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int brewing_stand = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int brewing_stand_base = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int brick = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int cactus_bottom = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int cactus_side = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int cactus_top = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int cake_bottom = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int cake_inner = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int cake_side = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int cake_top = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int carrots_stage_0 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int carrots_stage_1 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int carrots_stage_2 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int carrots_stage_3 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int cauldron_bottom = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int cauldron_inner = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int cauldron_side = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int cauldron_top = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int clay = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int coal_block = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int coal_ore = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int coarse_dirt = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int cobblestone = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int cobblestone_mossy = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int cocoa_stage_0 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int cocoa_stage_1 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int cocoa_stage_2 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int command_block = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int comparator_off = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int comparator_on = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int crafting_table_front = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int crafting_table_side = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int crafting_table_top = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int daylight_detector_inverted_top = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int daylight_detector_side = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int daylight_detector_top = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int deadbush = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int destroy_stage_0 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int destroy_stage_1 = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int destroy_stage_2 = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int destroy_stage_3 = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int destroy_stage_4 = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int destroy_stage_5 = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int destroy_stage_6 = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int destroy_stage_7 = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int destroy_stage_8 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int destroy_stage_9 = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int diamond_block = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int diamond_ore = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int dirt = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int dirt_podzol_side = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int dirt_podzol_top = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int dispenser_front_horizontal = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int dispenser_front_vertical = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int door_acacia_lower = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int door_acacia_upper = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int door_birch_lower = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int door_birch_upper = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int door_dark_oak_lower = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int door_dark_oak_upper = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int door_iron_lower = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int door_iron_upper = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int door_jungle_lower = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int door_jungle_upper = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int door_spruce_lower = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int door_spruce_upper = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int door_wood_lower = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int door_wood_upper = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int double_plant_fern_bottom = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int double_plant_fern_top = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int double_plant_grass_bottom = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int double_plant_grass_top = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int double_plant_paeonia_bottom = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int double_plant_paeonia_top = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int double_plant_rose_bottom = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int double_plant_rose_top = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int double_plant_sunflower_back = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int double_plant_sunflower_bottom = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int double_plant_sunflower_front = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int double_plant_sunflower_top = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int double_plant_syringa_bottom = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int double_plant_syringa_top = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int dragon_egg = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int dropper_front_horizontal = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int dropper_front_vertical = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int emerald_block = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int emerald_ore = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int enchanting_table_bottom = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int enchanting_table_side = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int enchanting_table_top = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int end_stone = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int endframe_eye = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int endframe_side = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int endframe_top = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int farmland_dry = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int farmland_wet = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int fern = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int fire_layer_0 = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int fire_layer_1 = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int flower_allium = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int flower_blue_orchid = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int flower_dandelion = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int flower_houstonia = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int flower_oxeye_daisy = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int flower_paeonia = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int flower_pot = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int flower_rose = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int flower_tulip_orange = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int flower_tulip_pink = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int flower_tulip_red = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public const int flower_tulip_white = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public const int furnace_front_off = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public const int furnace_front_on = 2130837629;
			
			// aapt resource value: 0x7f02007e
			public const int furnace_side = 2130837630;
			
			// aapt resource value: 0x7f02007f
			public const int furnace_top = 2130837631;
			
			// aapt resource value: 0x7f020080
			public const int glass = 2130837632;
			
			// aapt resource value: 0x7f020081
			public const int glass_black = 2130837633;
			
			// aapt resource value: 0x7f020082
			public const int glass_blue = 2130837634;
			
			// aapt resource value: 0x7f020083
			public const int glass_brown = 2130837635;
			
			// aapt resource value: 0x7f020084
			public const int glass_cyan = 2130837636;
			
			// aapt resource value: 0x7f020085
			public const int glass_gray = 2130837637;
			
			// aapt resource value: 0x7f020086
			public const int glass_green = 2130837638;
			
			// aapt resource value: 0x7f020087
			public const int glass_light_blue = 2130837639;
			
			// aapt resource value: 0x7f020088
			public const int glass_lime = 2130837640;
			
			// aapt resource value: 0x7f020089
			public const int glass_magenta = 2130837641;
			
			// aapt resource value: 0x7f02008a
			public const int glass_orange = 2130837642;
			
			// aapt resource value: 0x7f02008b
			public const int glass_pane_top = 2130837643;
			
			// aapt resource value: 0x7f02008c
			public const int glass_pane_top_black = 2130837644;
			
			// aapt resource value: 0x7f02008d
			public const int glass_pane_top_blue = 2130837645;
			
			// aapt resource value: 0x7f02008e
			public const int glass_pane_top_brown = 2130837646;
			
			// aapt resource value: 0x7f02008f
			public const int glass_pane_top_cyan = 2130837647;
			
			// aapt resource value: 0x7f020090
			public const int glass_pane_top_gray = 2130837648;
			
			// aapt resource value: 0x7f020091
			public const int glass_pane_top_green = 2130837649;
			
			// aapt resource value: 0x7f020092
			public const int glass_pane_top_light_blue = 2130837650;
			
			// aapt resource value: 0x7f020093
			public const int glass_pane_top_lime = 2130837651;
			
			// aapt resource value: 0x7f020094
			public const int glass_pane_top_magenta = 2130837652;
			
			// aapt resource value: 0x7f020095
			public const int glass_pane_top_orange = 2130837653;
			
			// aapt resource value: 0x7f020096
			public const int glass_pane_top_pink = 2130837654;
			
			// aapt resource value: 0x7f020097
			public const int glass_pane_top_purple = 2130837655;
			
			// aapt resource value: 0x7f020098
			public const int glass_pane_top_red = 2130837656;
			
			// aapt resource value: 0x7f020099
			public const int glass_pane_top_silver = 2130837657;
			
			// aapt resource value: 0x7f02009a
			public const int glass_pane_top_white = 2130837658;
			
			// aapt resource value: 0x7f02009b
			public const int glass_pane_top_yellow = 2130837659;
			
			// aapt resource value: 0x7f02009c
			public const int glass_pink = 2130837660;
			
			// aapt resource value: 0x7f02009d
			public const int glass_purple = 2130837661;
			
			// aapt resource value: 0x7f02009e
			public const int glass_red = 2130837662;
			
			// aapt resource value: 0x7f02009f
			public const int glass_silver = 2130837663;
			
			// aapt resource value: 0x7f0200a0
			public const int glass_white = 2130837664;
			
			// aapt resource value: 0x7f0200a1
			public const int glass_yellow = 2130837665;
			
			// aapt resource value: 0x7f0200a2
			public const int glowstone = 2130837666;
			
			// aapt resource value: 0x7f0200a3
			public const int gold_block = 2130837667;
			
			// aapt resource value: 0x7f0200a4
			public const int gold_ore = 2130837668;
			
			// aapt resource value: 0x7f0200a5
			public const int grass_side = 2130837669;
			
			// aapt resource value: 0x7f0200a6
			public const int grass_side_overlay = 2130837670;
			
			// aapt resource value: 0x7f0200a7
			public const int grass_side_snowed = 2130837671;
			
			// aapt resource value: 0x7f0200a8
			public const int grass_top = 2130837672;
			
			// aapt resource value: 0x7f0200a9
			public const int gravel = 2130837673;
			
			// aapt resource value: 0x7f0200aa
			public const int hardened_clay = 2130837674;
			
			// aapt resource value: 0x7f0200ab
			public const int hardened_clay_stained_black = 2130837675;
			
			// aapt resource value: 0x7f0200ac
			public const int hardened_clay_stained_blue = 2130837676;
			
			// aapt resource value: 0x7f0200ad
			public const int hardened_clay_stained_brown = 2130837677;
			
			// aapt resource value: 0x7f0200ae
			public const int hardened_clay_stained_cyan = 2130837678;
			
			// aapt resource value: 0x7f0200af
			public const int hardened_clay_stained_gray = 2130837679;
			
			// aapt resource value: 0x7f0200b0
			public const int hardened_clay_stained_green = 2130837680;
			
			// aapt resource value: 0x7f0200b1
			public const int hardened_clay_stained_light_blue = 2130837681;
			
			// aapt resource value: 0x7f0200b2
			public const int hardened_clay_stained_lime = 2130837682;
			
			// aapt resource value: 0x7f0200b3
			public const int hardened_clay_stained_magenta = 2130837683;
			
			// aapt resource value: 0x7f0200b4
			public const int hardened_clay_stained_orange = 2130837684;
			
			// aapt resource value: 0x7f0200b5
			public const int hardened_clay_stained_pink = 2130837685;
			
			// aapt resource value: 0x7f0200b6
			public const int hardened_clay_stained_purple = 2130837686;
			
			// aapt resource value: 0x7f0200b7
			public const int hardened_clay_stained_red = 2130837687;
			
			// aapt resource value: 0x7f0200b8
			public const int hardened_clay_stained_silver = 2130837688;
			
			// aapt resource value: 0x7f0200b9
			public const int hardened_clay_stained_white = 2130837689;
			
			// aapt resource value: 0x7f0200ba
			public const int hardened_clay_stained_yellow = 2130837690;
			
			// aapt resource value: 0x7f0200bb
			public const int hay_block_side = 2130837691;
			
			// aapt resource value: 0x7f0200bc
			public const int hay_block_top = 2130837692;
			
			// aapt resource value: 0x7f0200bd
			public const int hopper_inside = 2130837693;
			
			// aapt resource value: 0x7f0200be
			public const int hopper_outside = 2130837694;
			
			// aapt resource value: 0x7f0200bf
			public const int hopper_top = 2130837695;
			
			// aapt resource value: 0x7f0200c0
			public const int ice = 2130837696;
			
			// aapt resource value: 0x7f0200c1
			public const int ice_packed = 2130837697;
			
			// aapt resource value: 0x7f0200c2
			public const int iron_bars = 2130837698;
			
			// aapt resource value: 0x7f0200c3
			public const int iron_block = 2130837699;
			
			// aapt resource value: 0x7f0200c4
			public const int iron_ore = 2130837700;
			
			// aapt resource value: 0x7f0200c5
			public const int iron_trapdoor = 2130837701;
			
			// aapt resource value: 0x7f0200c6
			public const int itemframe_background = 2130837702;
			
			// aapt resource value: 0x7f0200c7
			public const int jukebox_side = 2130837703;
			
			// aapt resource value: 0x7f0200c8
			public const int jukebox_top = 2130837704;
			
			// aapt resource value: 0x7f0200c9
			public const int ladder = 2130837705;
			
			// aapt resource value: 0x7f0200ca
			public const int lapis_block = 2130837706;
			
			// aapt resource value: 0x7f0200cb
			public const int lapis_ore = 2130837707;
			
			// aapt resource value: 0x7f0200cc
			public const int lava_flow = 2130837708;
			
			// aapt resource value: 0x7f0200cd
			public const int lava_still = 2130837709;
			
			// aapt resource value: 0x7f0200ce
			public const int leaves_acacia = 2130837710;
			
			// aapt resource value: 0x7f0200cf
			public const int leaves_big_oak = 2130837711;
			
			// aapt resource value: 0x7f0200d0
			public const int leaves_birch = 2130837712;
			
			// aapt resource value: 0x7f0200d1
			public const int leaves_jungle = 2130837713;
			
			// aapt resource value: 0x7f0200d2
			public const int leaves_oak = 2130837714;
			
			// aapt resource value: 0x7f0200d3
			public const int leaves_spruce = 2130837715;
			
			// aapt resource value: 0x7f0200d4
			public const int lever = 2130837716;
			
			// aapt resource value: 0x7f0200d5
			public const int log_acacia = 2130837717;
			
			// aapt resource value: 0x7f0200d6
			public const int log_acacia_top = 2130837718;
			
			// aapt resource value: 0x7f0200d7
			public const int log_big_oak = 2130837719;
			
			// aapt resource value: 0x7f0200d8
			public const int log_big_oak_top = 2130837720;
			
			// aapt resource value: 0x7f0200d9
			public const int log_birch = 2130837721;
			
			// aapt resource value: 0x7f0200da
			public const int log_birch_top = 2130837722;
			
			// aapt resource value: 0x7f0200db
			public const int log_jungle = 2130837723;
			
			// aapt resource value: 0x7f0200dc
			public const int log_jungle_top = 2130837724;
			
			// aapt resource value: 0x7f0200dd
			public const int log_oak = 2130837725;
			
			// aapt resource value: 0x7f0200de
			public const int log_oak_top = 2130837726;
			
			// aapt resource value: 0x7f0200df
			public const int log_spruce = 2130837727;
			
			// aapt resource value: 0x7f0200e0
			public const int log_spruce_top = 2130837728;
			
			// aapt resource value: 0x7f0200e1
			public const int melon_side = 2130837729;
			
			// aapt resource value: 0x7f0200e2
			public const int melon_stem_connected = 2130837730;
			
			// aapt resource value: 0x7f0200e3
			public const int melon_stem_disconnected = 2130837731;
			
			// aapt resource value: 0x7f0200e4
			public const int melon_top = 2130837732;
			
			// aapt resource value: 0x7f0200e5
			public const int mob_spawner = 2130837733;
			
			// aapt resource value: 0x7f0200e6
			public const int mushroom_block_inside = 2130837734;
			
			// aapt resource value: 0x7f0200e7
			public const int mushroom_block_skin_brown = 2130837735;
			
			// aapt resource value: 0x7f0200e8
			public const int mushroom_block_skin_red = 2130837736;
			
			// aapt resource value: 0x7f0200e9
			public const int mushroom_block_skin_stem = 2130837737;
			
			// aapt resource value: 0x7f0200ea
			public const int mushroom_brown = 2130837738;
			
			// aapt resource value: 0x7f0200eb
			public const int mushroom_red = 2130837739;
			
			// aapt resource value: 0x7f0200ec
			public const int mycelium_side = 2130837740;
			
			// aapt resource value: 0x7f0200ed
			public const int mycelium_top = 2130837741;
			
			// aapt resource value: 0x7f0200ee
			public const int nether_brick = 2130837742;
			
			// aapt resource value: 0x7f0200ef
			public const int nether_wart_stage_0 = 2130837743;
			
			// aapt resource value: 0x7f0200f0
			public const int nether_wart_stage_1 = 2130837744;
			
			// aapt resource value: 0x7f0200f1
			public const int nether_wart_stage_2 = 2130837745;
			
			// aapt resource value: 0x7f0200f2
			public const int netherrack = 2130837746;
			
			// aapt resource value: 0x7f0200f3
			public const int noteblock = 2130837747;
			
			// aapt resource value: 0x7f0200f4
			public const int obsidian = 2130837748;
			
			// aapt resource value: 0x7f0200f5
			public const int piston_bottom = 2130837749;
			
			// aapt resource value: 0x7f0200f6
			public const int piston_inner = 2130837750;
			
			// aapt resource value: 0x7f0200f7
			public const int piston_side = 2130837751;
			
			// aapt resource value: 0x7f0200f8
			public const int piston_top_normal = 2130837752;
			
			// aapt resource value: 0x7f0200f9
			public const int piston_top_sticky = 2130837753;
			
			// aapt resource value: 0x7f0200fa
			public const int planks_acacia = 2130837754;
			
			// aapt resource value: 0x7f0200fb
			public const int planks_big_oak = 2130837755;
			
			// aapt resource value: 0x7f0200fc
			public const int planks_birch = 2130837756;
			
			// aapt resource value: 0x7f0200fd
			public const int planks_jungle = 2130837757;
			
			// aapt resource value: 0x7f0200fe
			public const int planks_oak = 2130837758;
			
			// aapt resource value: 0x7f0200ff
			public const int planks_spruce = 2130837759;
			
			// aapt resource value: 0x7f020100
			public const int portal = 2130837760;
			
			// aapt resource value: 0x7f020101
			public const int potatoes_stage_0 = 2130837761;
			
			// aapt resource value: 0x7f020102
			public const int potatoes_stage_1 = 2130837762;
			
			// aapt resource value: 0x7f020103
			public const int potatoes_stage_2 = 2130837763;
			
			// aapt resource value: 0x7f020104
			public const int potatoes_stage_3 = 2130837764;
			
			// aapt resource value: 0x7f020105
			public const int prismarine_bricks = 2130837765;
			
			// aapt resource value: 0x7f020106
			public const int prismarine_dark = 2130837766;
			
			// aapt resource value: 0x7f020107
			public const int prismarine_rough = 2130837767;
			
			// aapt resource value: 0x7f020108
			public const int pumpkin_face_off = 2130837768;
			
			// aapt resource value: 0x7f020109
			public const int pumpkin_face_on = 2130837769;
			
			// aapt resource value: 0x7f02010a
			public const int pumpkin_side = 2130837770;
			
			// aapt resource value: 0x7f02010b
			public const int pumpkin_stem_connected = 2130837771;
			
			// aapt resource value: 0x7f02010c
			public const int pumpkin_stem_disconnected = 2130837772;
			
			// aapt resource value: 0x7f02010d
			public const int pumpkin_top = 2130837773;
			
			// aapt resource value: 0x7f02010e
			public const int quartz_block_bottom = 2130837774;
			
			// aapt resource value: 0x7f02010f
			public const int quartz_block_chiseled = 2130837775;
			
			// aapt resource value: 0x7f020110
			public const int quartz_block_chiseled_top = 2130837776;
			
			// aapt resource value: 0x7f020111
			public const int quartz_block_lines = 2130837777;
			
			// aapt resource value: 0x7f020112
			public const int quartz_block_lines_top = 2130837778;
			
			// aapt resource value: 0x7f020113
			public const int quartz_block_side = 2130837779;
			
			// aapt resource value: 0x7f020114
			public const int quartz_block_top = 2130837780;
			
			// aapt resource value: 0x7f020115
			public const int quartz_ore = 2130837781;
			
			// aapt resource value: 0x7f020116
			public const int rail_activator = 2130837782;
			
			// aapt resource value: 0x7f020117
			public const int rail_activator_powered = 2130837783;
			
			// aapt resource value: 0x7f020118
			public const int rail_detector = 2130837784;
			
			// aapt resource value: 0x7f020119
			public const int rail_detector_powered = 2130837785;
			
			// aapt resource value: 0x7f02011a
			public const int rail_golden = 2130837786;
			
			// aapt resource value: 0x7f02011b
			public const int rail_golden_powered = 2130837787;
			
			// aapt resource value: 0x7f02011c
			public const int rail_normal = 2130837788;
			
			// aapt resource value: 0x7f02011d
			public const int rail_normal_turned = 2130837789;
			
			// aapt resource value: 0x7f02011e
			public const int red_sand = 2130837790;
			
			// aapt resource value: 0x7f02011f
			public const int red_sandstone_bottom = 2130837791;
			
			// aapt resource value: 0x7f020120
			public const int red_sandstone_carved = 2130837792;
			
			// aapt resource value: 0x7f020121
			public const int red_sandstone_normal = 2130837793;
			
			// aapt resource value: 0x7f020122
			public const int red_sandstone_smooth = 2130837794;
			
			// aapt resource value: 0x7f020123
			public const int red_sandstone_top = 2130837795;
			
			// aapt resource value: 0x7f020124
			public const int redstone_block = 2130837796;
			
			// aapt resource value: 0x7f020125
			public const int redstone_dust_cross = 2130837797;
			
			// aapt resource value: 0x7f020126
			public const int redstone_dust_cross_overlay = 2130837798;
			
			// aapt resource value: 0x7f020127
			public const int redstone_dust_line = 2130837799;
			
			// aapt resource value: 0x7f020128
			public const int redstone_dust_line_overlay = 2130837800;
			
			// aapt resource value: 0x7f020129
			public const int redstone_lamp_off = 2130837801;
			
			// aapt resource value: 0x7f02012a
			public const int redstone_lamp_on = 2130837802;
			
			// aapt resource value: 0x7f02012b
			public const int redstone_ore = 2130837803;
			
			// aapt resource value: 0x7f02012c
			public const int redstone_torch_off = 2130837804;
			
			// aapt resource value: 0x7f02012d
			public const int redstone_torch_on = 2130837805;
			
			// aapt resource value: 0x7f02012e
			public const int reeds = 2130837806;
			
			// aapt resource value: 0x7f02012f
			public const int repeater_off = 2130837807;
			
			// aapt resource value: 0x7f020130
			public const int repeater_on = 2130837808;
			
			// aapt resource value: 0x7f020131
			public const int sand = 2130837809;
			
			// aapt resource value: 0x7f020132
			public const int sandstone_bottom = 2130837810;
			
			// aapt resource value: 0x7f020133
			public const int sandstone_carved = 2130837811;
			
			// aapt resource value: 0x7f020134
			public const int sandstone_normal = 2130837812;
			
			// aapt resource value: 0x7f020135
			public const int sandstone_smooth = 2130837813;
			
			// aapt resource value: 0x7f020136
			public const int sandstone_top = 2130837814;
			
			// aapt resource value: 0x7f020137
			public const int sapling_acacia = 2130837815;
			
			// aapt resource value: 0x7f020138
			public const int sapling_birch = 2130837816;
			
			// aapt resource value: 0x7f020139
			public const int sapling_jungle = 2130837817;
			
			// aapt resource value: 0x7f02013a
			public const int sapling_oak = 2130837818;
			
			// aapt resource value: 0x7f02013b
			public const int sapling_roofed_oak = 2130837819;
			
			// aapt resource value: 0x7f02013c
			public const int sapling_spruce = 2130837820;
			
			// aapt resource value: 0x7f02013d
			public const int sea_lantern = 2130837821;
			
			// aapt resource value: 0x7f02013e
			public const int slime = 2130837822;
			
			// aapt resource value: 0x7f02013f
			public const int snow = 2130837823;
			
			// aapt resource value: 0x7f020140
			public const int soul_sand = 2130837824;
			
			// aapt resource value: 0x7f020141
			public const int stone = 2130837825;
			
			// aapt resource value: 0x7f020142
			public const int stone_andesite = 2130837826;
			
			// aapt resource value: 0x7f020143
			public const int stone_andesite_smooth = 2130837827;
			
			// aapt resource value: 0x7f020144
			public const int stone_diorite = 2130837828;
			
			// aapt resource value: 0x7f020145
			public const int stone_diorite_smooth = 2130837829;
			
			// aapt resource value: 0x7f020146
			public const int stone_granite = 2130837830;
			
			// aapt resource value: 0x7f020147
			public const int stone_granite_smooth = 2130837831;
			
			// aapt resource value: 0x7f020148
			public const int stone_slab_side = 2130837832;
			
			// aapt resource value: 0x7f020149
			public const int stone_slab_top = 2130837833;
			
			// aapt resource value: 0x7f02014a
			public const int stonebrick = 2130837834;
			
			// aapt resource value: 0x7f02014b
			public const int stonebrick_carved = 2130837835;
			
			// aapt resource value: 0x7f02014c
			public const int stonebrick_cracked = 2130837836;
			
			// aapt resource value: 0x7f02014d
			public const int stonebrick_mossy = 2130837837;
			
			// aapt resource value: 0x7f02014e
			public const int tallgrass = 2130837838;
			
			// aapt resource value: 0x7f02014f
			public const int tnt_bottom = 2130837839;
			
			// aapt resource value: 0x7f020150
			public const int tnt_side = 2130837840;
			
			// aapt resource value: 0x7f020151
			public const int tnt_top = 2130837841;
			
			// aapt resource value: 0x7f020152
			public const int torch_on = 2130837842;
			
			// aapt resource value: 0x7f020153
			public const int trapdoor = 2130837843;
			
			// aapt resource value: 0x7f020154
			public const int trip_wire = 2130837844;
			
			// aapt resource value: 0x7f020155
			public const int trip_wire_source = 2130837845;
			
			// aapt resource value: 0x7f020156
			public const int vine = 2130837846;
			
			// aapt resource value: 0x7f020157
			public const int water_flow = 2130837847;
			
			// aapt resource value: 0x7f020158
			public const int water_still = 2130837848;
			
			// aapt resource value: 0x7f020159
			public const int waterlily = 2130837849;
			
			// aapt resource value: 0x7f02015a
			public const int web = 2130837850;
			
			// aapt resource value: 0x7f02015b
			public const int wheat_stage_0 = 2130837851;
			
			// aapt resource value: 0x7f02015c
			public const int wheat_stage_1 = 2130837852;
			
			// aapt resource value: 0x7f02015d
			public const int wheat_stage_2 = 2130837853;
			
			// aapt resource value: 0x7f02015e
			public const int wheat_stage_3 = 2130837854;
			
			// aapt resource value: 0x7f02015f
			public const int wheat_stage_4 = 2130837855;
			
			// aapt resource value: 0x7f020160
			public const int wheat_stage_5 = 2130837856;
			
			// aapt resource value: 0x7f020161
			public const int wheat_stage_6 = 2130837857;
			
			// aapt resource value: 0x7f020162
			public const int wheat_stage_7 = 2130837858;
			
			// aapt resource value: 0x7f020163
			public const int wool_colored_black = 2130837859;
			
			// aapt resource value: 0x7f020164
			public const int wool_colored_blue = 2130837860;
			
			// aapt resource value: 0x7f020165
			public const int wool_colored_brown = 2130837861;
			
			// aapt resource value: 0x7f020166
			public const int wool_colored_cyan = 2130837862;
			
			// aapt resource value: 0x7f020167
			public const int wool_colored_gray = 2130837863;
			
			// aapt resource value: 0x7f020168
			public const int wool_colored_green = 2130837864;
			
			// aapt resource value: 0x7f020169
			public const int wool_colored_light_blue = 2130837865;
			
			// aapt resource value: 0x7f02016a
			public const int wool_colored_lime = 2130837866;
			
			// aapt resource value: 0x7f02016b
			public const int wool_colored_magenta = 2130837867;
			
			// aapt resource value: 0x7f02016c
			public const int wool_colored_orange = 2130837868;
			
			// aapt resource value: 0x7f02016d
			public const int wool_colored_pink = 2130837869;
			
			// aapt resource value: 0x7f02016e
			public const int wool_colored_purple = 2130837870;
			
			// aapt resource value: 0x7f02016f
			public const int wool_colored_red = 2130837871;
			
			// aapt resource value: 0x7f020170
			public const int wool_colored_silver = 2130837872;
			
			// aapt resource value: 0x7f020171
			public const int wool_colored_white = 2130837873;
			
			// aapt resource value: 0x7f020172
			public const int wool_colored_yellow = 2130837874;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080007
			public const int defaultButton = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int frameLayout2 = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int gridLayout1 = 2131230729;
			
			// aapt resource value: 0x7f080000
			public const int gridView1 = 2131230720;
			
			// aapt resource value: 0x7f08000a
			public const int imageView1 = 2131230730;
			
			// aapt resource value: 0x7f080013
			public const int imageView10 = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int imageView11 = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int imageView12 = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int imageView13 = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int imageView14 = 2131230743;
			
			// aapt resource value: 0x7f080018
			public const int imageView15 = 2131230744;
			
			// aapt resource value: 0x7f080019
			public const int imageView16 = 2131230745;
			
			// aapt resource value: 0x7f08001a
			public const int imageView17 = 2131230746;
			
			// aapt resource value: 0x7f08001b
			public const int imageView18 = 2131230747;
			
			// aapt resource value: 0x7f08001c
			public const int imageView19 = 2131230748;
			
			// aapt resource value: 0x7f08000b
			public const int imageView2 = 2131230731;
			
			// aapt resource value: 0x7f08001d
			public const int imageView20 = 2131230749;
			
			// aapt resource value: 0x7f08001e
			public const int imageView21 = 2131230750;
			
			// aapt resource value: 0x7f08001f
			public const int imageView22 = 2131230751;
			
			// aapt resource value: 0x7f080020
			public const int imageView23 = 2131230752;
			
			// aapt resource value: 0x7f080021
			public const int imageView24 = 2131230753;
			
			// aapt resource value: 0x7f08000c
			public const int imageView3 = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int imageView4 = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int imageView5 = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int imageView6 = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int imageView7 = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int imageView8 = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int imageView9 = 2131230738;
			
			// aapt resource value: 0x7f080004
			public const int myButton = 2131230724;
			
			// aapt resource value: 0x7f080025
			public const int randomGenText = 2131230757;
			
			// aapt resource value: 0x7f080022
			public const int space1 = 2131230754;
			
			// aapt resource value: 0x7f080001
			public const int space2 = 2131230721;
			
			// aapt resource value: 0x7f080023
			public const int space3 = 2131230755;
			
			// aapt resource value: 0x7f080002
			public const int space4 = 2131230722;
			
			// aapt resource value: 0x7f080006
			public const int space5 = 2131230726;
			
			// aapt resource value: 0x7f080024
			public const int textView1 = 2131230756;
			
			// aapt resource value: 0x7f080005
			public const int textView2 = 2131230725;
			
			// aapt resource value: 0x7f080003
			public const int toolbar1 = 2131230723;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int button_default = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int debug_info = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int default_no_random = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int success_default = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int success_random = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int utility_name = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_RedstoneDefaults = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
